### ISSUE TITLE
PortableFont fails on mobile

### ISSUE THREAD

**Issue by TonyHoyleRps** [i-e-b/Formation#1]
PortableFont uses Assembly.GetExecutingAssembly().Location to determine its location, but this is unreliable and will often return an empty string on non-windows platforms, causing the library to throw an exception.

Microsoft recommend AppContext.BaseDirectory for this.

**Comment by i-e-b** [comment]
Thanks for the contribution.
Code is updated, new NuGet packages available at

- https://www.nuget.org/packages/PortableGdi/0.0.3
- https://www.nuget.org/packages/PortablePdfSharpStd/0.0.6
- https://www.nuget.org/packages/Form8sn/1.5.3
